services:
  rdf-delta-server:
    container_name: rdf-delta-server
    build:
      context: .
    networks:
      - stack
    ports:
      - 1066:1066
    volumes:
      - rdf_delta_data:/opt/rdf-delta/databases
    profiles:
      - stack

  fuseki:
    container_name: fuseki
    build:
      context: .
    networks:
      - stack
    ports:
      - 3030:3030
    volumes:
      - fuseki_data:/fuseki
    command: ["/bin/bash", "-c", "/opt/rdf-delta/fuseki-entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rdf-delta-server:1066"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s
    profiles:
      - stack

  fuseki2:
    container_name: fuseki2
    build:
      context: .
    ports:
      - 3031:3030
    networks:
      - stack
    volumes:
      - fuseki2_data:/fuseki
    command: /bin/bash -c /opt/rdf-delta/fuseki-entrypoint.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rdf-delta-server:1066"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s
    profiles:
      - stack

  loader:
    container_name: data-loader
    image: conjecto/rdf-delta:1.1.2
    networks:
      - stack
    volumes:
      - ./data.ttl:/opt/rdf-delta/data.ttl
    command: append --server http://rdf-delta-server:1066 --log ds /opt/rdf-delta/data.ttl
    profiles:
      - data-loader

volumes:
  rdf_delta_data:
  fuseki_data:
  fuseki2_data:

networks:
  stack:
