# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: list all tasks
    cmd: task -a

  up:
    desc: start delta server and 2 fuseki servers as docker compose services
    cmd: docker compose up -d

  load:
    desc: Load data.trig as a patch update
    cmd: uv run load_patch.py

  down:
    desc: down the docker services
    cmd: docker compose down

