# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: list all tasks
    cmd: task -a

  up:
    desc: start delta server and 2 fuseki servers as docker compose services
    cmd: docker compose up -d --build

  restart:
    desc: Restart both fuseki servers
    cmd: docker compose restart fuseki1 fuseki2

  load:
    desc: Load data.trig as a patch update
    cmd: uv run load_patch.py

  query:
    desc: Execute a set of queries against the databases
    cmd: uv run query.py

  down:
    desc: down the docker services
    cmd: docker compose down
